name: Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python3 -m pip install build --user
      - run: python3 -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
